"""
agent/tools/test_tools.py
--------------------------
Safe utilities for validating generated test structures.

SECURITY RULES enforced by this module:
  - Never execute any repository or generated code.
  - Never use shell=True or subprocess with user-controlled input.
  - Never write any files to disk.
  - ast.parse() is used only to validate syntax, never to execute code.

Public API:
    TestCase          — dataclass for a single structured test case
    TestSuite         — dataclass holding a collection of TestCases
    ValidationResult  — dataclass for a validation outcome
    validate_test_syntax(source)           → ValidationResult
    validate_test_suite(suite)             → ValidationResult
    parse_test_cases_from_text(text)       → List[TestCase]
    validate_proposed_patch_structure(diff_text) → ValidationResult
    check_test_targets_exist(suite, repo_root)   → ValidationResult
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class TestCase:
    """A single structured test case generated by the LLM."""
    objective:   str                     # What this test verifies
    target_file: str                     # Relative path of the file under test
    target_func: str                     # Function or method being tested
    test_type:   str                     # e.g. "regression", "unit", "edge_case"
    input_data:  str                     # Input / precondition description
    expected:    str                     # Expected result / behaviour
    rationale:   str                     # Why this test validates the fix
    test_code:   str = ""                # Optional: generated pytest snippet


@dataclass
class TestSuite:
    """Collection of test cases for a single pipeline run."""
    cases: List[TestCase] = field(default_factory=list)
    raw_source: str        = ""          # Full pytest source (if generated)

    @property
    def has_cases(self) -> bool:
        return len(self.cases) > 0

    @property
    def has_source(self) -> bool:
        return bool(self.raw_source.strip())


@dataclass
class ValidationResult:
    """Outcome of a validation check."""
    valid:    bool
    issues:   List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def add_issue(self, msg: str) -> None:
        self.issues.append(msg)
        self.valid = False

    def add_warning(self, msg: str) -> None:
        self.warnings.append(msg)


# ---------------------------------------------------------------------------
# Syntax validation
# ---------------------------------------------------------------------------

def validate_test_syntax(source: str) -> ValidationResult:
    """
    Check whether *source* is valid Python using ast.parse().

    Never executes the code — parse-only.

    Returns:
        ValidationResult with valid=True if the syntax is correct.
    """
    result = ValidationResult(valid=True)

    if not source or not source.strip():
        result.add_issue("Test source is empty.")
        return result

    try:
        ast.parse(source, filename="<generated_tests>", type_comments=False)
    except SyntaxError as exc:
        result.add_issue(f"SyntaxError at line {exc.lineno}: {exc.msg}")
    except Exception as exc:     # pragma: no cover — unexpected parser errors
        result.add_issue(f"Parse error: {exc}")

    return result


def _has_test_functions(source: str) -> bool:
    """Return True if *source* contains at least one function named test_*."""
    try:
        tree = ast.parse(source)
        return any(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name.startswith("test_")
            for node in ast.walk(tree)
        )
    except SyntaxError:
        return False


# ---------------------------------------------------------------------------
# TestSuite validation
# ---------------------------------------------------------------------------

def validate_test_suite(suite: TestSuite) -> ValidationResult:
    """
    Validate the structure and content of a TestSuite.

    Checks:
      - At least one test case present.
      - Each case has a non-empty objective, target_file, and expected.
      - If raw_source is present, it must have valid Python syntax and
        contain at least one test_* function.

    Does NOT execute anything.
    """
    result = ValidationResult(valid=True)

    if not suite.has_cases and not suite.has_source:
        result.add_issue("TestSuite has no test cases and no source code.")
        return result

    # Per-case validation
    for i, case in enumerate(suite.cases):
        if not case.objective.strip():
            result.add_issue(f"Case {i}: missing 'objective'.")
        if not case.target_file.strip():
            result.add_issue(f"Case {i}: missing 'target_file'.")
        if not case.expected.strip():
            result.add_issue(f"Case {i}: missing 'expected' result.")
        if not case.target_func.strip():
            result.add_warning(f"Case {i}: 'target_func' is empty.")

    # Source validation when present
    if suite.has_source:
        syntax_result = validate_test_syntax(suite.raw_source)
        result.issues.extend(syntax_result.issues)
        result.warnings.extend(syntax_result.warnings)
        if not syntax_result.issues and not _has_test_functions(suite.raw_source):
            result.add_warning(
                "Generated source contains no functions named test_*. "
                "pytest may not discover any tests."
            )
        if syntax_result.issues:
            result.valid = False

    return result


# ---------------------------------------------------------------------------
# Parsing structured LLM output into TestCase objects
# ---------------------------------------------------------------------------

_CASE_BLOCK_RE = re.compile(
    r"TEST_CASE\s*(?:\d+)?\s*:\s*\n(.*?)(?=TEST_CASE\s*(?:\d+)?\s*:|$)",
    re.DOTALL | re.IGNORECASE,
)

_FIELD_RE = re.compile(
    r"^(OBJECTIVE|TARGET_FILE|TARGET_FUNC|TEST_TYPE|INPUT|EXPECTED|RATIONALE)\s*:\s*(.+)",
    re.IGNORECASE | re.MULTILINE,
)


def parse_test_cases_from_text(text: str) -> List[TestCase]:
    """
    Extract TestCase objects from a structured LLM response.

    The expected format is one or more TEST_CASE blocks:

        TEST_CASE 1:
        OBJECTIVE: Verify that get_items raises IndexError on empty list
        TARGET_FILE: utils.py
        TARGET_FUNC: get_items
        TEST_TYPE: regression
        INPUT: get_items([], 0)
        EXPECTED: IndexError raised
        RATIONALE: Directly tests the reported bug scenario

    Returns an empty list if no parseable blocks are found.
    Never raises.
    """
    cases: List[TestCase] = []

    for block_match in _CASE_BLOCK_RE.finditer(text):
        block = block_match.group(1)
        fields: dict[str, str] = {}
        for m in _FIELD_RE.finditer(block):
            fields[m.group(1).upper()] = m.group(2).strip()

        if not fields.get("OBJECTIVE") and not fields.get("TARGET_FILE"):
            continue   # skip empty / noise blocks

        cases.append(TestCase(
            objective=fields.get("OBJECTIVE",   ""),
            target_file=fields.get("TARGET_FILE", ""),
            target_func=fields.get("TARGET_FUNC", ""),
            test_type=fields.get("TEST_TYPE",   "regression"),
            input_data=fields.get("INPUT",       ""),
            expected=fields.get("EXPECTED",    ""),
            rationale=fields.get("RATIONALE",  ""),
        ))

    return cases


# ---------------------------------------------------------------------------
# Patch structure validation (deterministic, no LLM)
# ---------------------------------------------------------------------------

def validate_proposed_patch_structure(diff_text: str) -> ValidationResult:
    """
    Inspect a unified-diff string for basic structural validity.

    Does NOT apply or execute the patch.
    Checks:
      - Non-empty diff.
      - Contains at least one hunk header (@@).
      - Does not look like a pure-stub / placeholder comment only.

    Returns ValidationResult.
    """
    result = ValidationResult(valid=True)

    if not diff_text or not diff_text.strip():
        result.add_issue("Proposed patch is empty.")
        return result

    stripped = diff_text.strip()

    # Check for hunk header — real unified diffs always have @@
    if "@@" not in stripped:
        # Could be a preview/stub — record as warning, not error
        result.add_warning(
            "Diff contains no hunk headers (@@). "
            "This may be a stub or description rather than a real unified diff."
        )

    # Check whether it's only comment lines (stub patch)
    non_comment_lines = [
        ln for ln in stripped.splitlines()
        if ln.strip() and not ln.strip().startswith("#")
    ]
    if not non_comment_lines:
        result.add_issue(
            "Proposed patch contains only comment/empty lines — no actual changes."
        )

    return result


# ---------------------------------------------------------------------------
# Target path existence check
# ---------------------------------------------------------------------------

def check_test_targets_exist(suite: TestSuite, repo_root: str) -> ValidationResult:
    """
    Check whether the target files referenced in *suite* exist inside *repo_root*.

    Does NOT traverse outside repo_root.
    Returns a ValidationResult with warnings for missing files.
    """
    result = ValidationResult(valid=True)

    if not repo_root or not Path(repo_root).is_dir():
        result.add_warning(f"Repository root not accessible: {repo_root!r}")
        return result

    root = Path(repo_root).resolve()

    for case in suite.cases:
        target = case.target_file.strip()
        if not target:
            continue
        # Security: resolve and check stays inside root
        try:
            resolved = (root / target).resolve()
            resolved.relative_to(root)   # raises ValueError if outside
        except ValueError:
            result.add_issue(
                f"Target file {target!r} resolves outside repository root — "
                "path traversal attempt."
            )
            result.valid = False
            continue

        if not resolved.exists():
            result.add_warning(f"Target file not found in repo: {target!r}")

    return result
